receivers:
  hostmetrics:
    collection_interval: 1m
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:
  otlp:
    protocols:
      grpc:

processors:
  resource:
    attributes:
      - key: host.name
        value: $HOSTNAME
        action: upsert
  batch:
    timeout: 200ms

exporters:
  logging:
    logLevel: info
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": $HNY_API_KEY
      "x-honeycomb-dataset": $HNY_DATASET_NAME

service:
  pipelines:
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [batch, resource]
      exporters: [otlp, logging]
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp, logging]
