receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:
      processes:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  resource:
    attributes:
      - key: host.name
        value: $HOSTNAME
        action: upsert
      - key: service.name
        value: webserver
        action: upsert
  batch:
    timeout: 200ms
  probabilistic_sampler:
    hash_seed: 22
    sampling_percentage: 15

exporters:
  logging:
    logLevel: debug
  otlp/traces:
    endpoint: "192.168.64.1:9090"
    insecure: true
    headers:
      "x-honeycomb-team": $HNY_API_KEY
      "x-honeycomb-dataset": ${HNY_DATASET_NAME}_traces
  otlp/metrics:
    endpoint: "192.168.64.1:9090"
    insecure: true
    headers:
      "x-honeycomb-team": $HNY_API_KEY
      "x-honeycomb-dataset": ${HNY_DATASET_NAME}_metrics

service:
  pipelines:
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [batch, resource]
      exporters: [otlp/metrics, logging]
    traces:
      receivers: [otlp]
      processors: [batch, resource, probabilistic_sampler]
      exporters: [otlp/traces, logging]
