---

- name: Update webservers
  hosts: webservers
  remote_user: ubuntu
  vars:
    hny_api_key: "{{ lookup('env', 'HNY_API_KEY') }}"
  tasks:

    - name: polyhedron | copy built files
      copy: src=../build/polyhedron-linux-amd64 dest=/home/ubuntu/polyhedron owner=ubuntu group=ubuntu mode=0770
      notify: reload polyhedron

    - name: polyhedron | copy service definition
      become: true
      copy: src=./polyhedron.service dest=/lib/systemd/system/polyhedron.service owner=ubuntu group=ubuntu mode=0644
      notify: reload polyhedron

    - name: polyhedron | service is running
      become: true
      service: name=polyhedron state=started

    - name: otelcol | download
      get_url:
        url: https://github.com/open-telemetry/opentelemetry-collector/releases/download/v0.27.0/otelcol_linux_amd64
        dest: /home/ubuntu/otelcol
        mode: 0770
        checksum: sha256:d3972b89f990a1227ab18963d131bf32ec9025261f6e63f32ec32671679e62bf

    - name: otelcol | copy config
      copy: src=./otelcol-config.yaml dest=/home/ubuntu/otelcol-config.yaml owner=ubuntu group=ubuntu mode=0644
      notify: reload otelcol

    - name: otelcol | copy start script
      template: src=./otelcol-start.j2 dest=/home/ubuntu/otelcol-start owner=ubuntu group=ubuntu mode=0774
      notify: reload otelcol
      
    - name: otelcol | copy service definition
      become: true
      copy: src=./otelcol.service dest=/lib/systemd/system/otelcol.service owner=ubuntu group=ubuntu mode=0644
      notify: reload otelcol

    - name: otelcol | service is started
      become: true
      service: name=otelcol state=started

  handlers:

    - name: reload polyhedron
      become: true
      service: name=polyhedron state=restarted

    - name: reload otelcol
      become: true
      service: name=otelcol state=restarted

- name: Update load balancers
  hosts: loadbalancers
  remote_user: ubuntu
  tasks:

    - name: nginx | install
      become: true
      apt: name=nginx

    - name: nginx | remove default server
      become: true
      file: path=/etc/nginx/sites-enabled/default state=absent

    - name: nginx | add load balancer config
      become: true
      notify: reload nginx
      copy: src=./nginx-load-balancer.conf dest=/etc/nginx/conf.d/load-balancer.conf mode=0644

    - name: nginx | ensure service is running
      become: true
      service: name=nginx state=started

  handlers:
    - name: reload nginx
      become: true
      service: name=nginx state=reloaded
